# Generated by Django 5.2.4 on 2025-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_date_for_reg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
